version: '3.4'

services:
  clubee-api:
    build:
      context: .
      dockerfile: Clubee.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      - JwtSettings__SecretKey=8BaypBYxaxT7DptQrxcR993AVG9f8Fz5msVqQUAKkGZ3EpxXvwpv8czak4XQ
      - JwtSettings__ExpirationSeconds=172800

      - Storage__Account=devstoreaccount1
      - Storage__Key=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      - storage__Address=clubee-storage
      - Storage__Port=10000
      - Storage__Protocol=http

      - MongoSettings__Connection=mongodb://clubee-database
      - MongoSettings__Database=clubee

    ports:
      - "52356:80"
    depends_on:
      - clubee-storage
      - clubee-database
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  clubee-storage:
    image: arafato/azurite
    ports: 
      - "10000:10000"

  clubee-database:
    image: mongo
    ports:
      - "27017:27017"